import streamlit as st
from logics import cmpb_info_handler

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="AMA about your pre-enlistee journey!"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("AMA about your pre-enlistee journey!")

form = st.form(key="form")
form.subheader("Unsure of what to expect?")

user_prompt = form.text_area("Ask me any question about your pre-enlistee journey, and we \
                             will try our best to answer!", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    response = cmpb_info_handler.process_query(user_prompt) # <--- This calls the helper function that we have created 🆕
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")

