import streamlit as st
from logics import vocation_chooser

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="Vocation chooser"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Vocation chooser")

form = st.form(key="form")
form.subheader("Having trouble choosing a vocation?")

user_prompt = form.text_area("Tell me more about yourself below, and we will help you choose \
                             a suitable vocation. 'e.g. I am hardworking and I love mathematics!'", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    response = vocation_chooser.process_user_message(user_prompt) # <--- This calls the helper function that we have created 🆕
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")

